version: '2'
services:
  trycodnet-api-php-fpm:
    build: .
    image: trycodnet-api-php-fpm
    ports:
      - '9002:9000'
  nginx:
    build: nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
